const TILESETS_CREATE = 'TILESETS_CREATE';
const TILESETS_ADD_TILE = 'TILESETS_ADD_TILE';
const TILESETS_ORDER_TILE = 'TILESETS_ORDER_TILE';
const TILESETS_REMOVE_TILE = 'TILESETS_REMOVE_TILE';
const TILESETS_SAVE = 'TILESETS_SAVE';
const TILESETS_LOAD = 'TILESETS_LOAD';

export {
  TILESETS_CREATE,
  TILESETS_ADD_TILE,
  TILESETS_ORDER_TILE,
  TILESETS_REMOVE_TILE,
  TILESETS_SAVE,
  TILESETS_LOAD,
};
